CREATE TABLE IF NOT EXISTS STUDENT(
    ROLL_NO TEXT PRIMARY KEY,
    NAME TEXT NOT NULL,
    ADDRESS TEXT,
    PHONE TEXT,
    AGE INTEGER
);
INSERT INTO STUDENT(ROLL_NO, NAME, ADDRESS, PHONE, AGE) VALUES
    ('5', 'JONES', 'FORNITE ISLAND', '*******', 3),
    ('9', 'PEELY', 'FORNITE ISLAND', '&&&&&&&&', 6),
    ('6', 'BRUCE', 'GOTHAM CITY', '%%%%%%%%%', 47),
    ('19', 'PETER', 'NEWYORK', '@@@@@@@@', 20);

SELECT * FROM STUDENT;
SELECT * FROM STUDENT WHERE AGE=47 AND ADDRESS='GOTHAM CITY';
SELECT * FROM STUDENT WHERE AGE=3 OR ADDRESS='FORTNITE ISLAND';
SELECT MIN(AGE) AS smallestage FROM STUDENT;
SELECT MAX(AGE) AS largestage FROM STUDENT;
